--BACKUP VÀ RESTORE: CSDL KHÔNG ÐANG LÀM VI?C
BACKUP DATABASE DIALYVN
TO DISK='C:\DIALYVN.BAK'


RESTORE DATABASE DIALYVN
FROM DISK='C:\DIALYVN.BAK'


WITH
	PASSWORD='123456'

--ATTACH VÀ DETACH


SP_DETACH_DB DIALYVN

CREATE DATABASE DIALYVN
ON(FILENAME='C:\DIALYVN.MDF')
FOR ATTACH